//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureApp.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DayNightDbEntities : DbContext
    {
        public DayNightDbEntities()
            : base("name=DayNightDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_About> Tbl_About { get; set; }
        public virtual DbSet<Tbl_Contact> Tbl_Contact { get; set; }
        public virtual DbSet<Tbl_Employee> Tbl_Employee { get; set; }
        public virtual DbSet<Tbl_Feature> Tbl_Feature { get; set; }
        public virtual DbSet<Tbl_Question> Tbl_Question { get; set; }
        public virtual DbSet<Tbl_Service> Tbl_Service { get; set; }
        public virtual DbSet<Tbl_SubFeature> Tbl_SubFeature { get; set; }
        public virtual DbSet<Tbl_Testimonial> Tbl_Testimonial { get; set; }
    }
}
