//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureApp.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeePhotoURL { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeTitle { get; set; }
        public string EmployeeFacebook { get; set; }
        public string EmployeeX { get; set; }
        public string EmployeeLinkedin { get; set; }
        public string EmployeeInstagram { get; set; }
    }
}
