//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureApp.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Feature
    {
        public int FeatureId { get; set; }
        public string FeatureTitle { get; set; }
        public string FeatureDescription { get; set; }
        public string FeatureSubDescription { get; set; }
        public string FeatureLink { get; set; }
        public string VideoURL { get; set; }
        public string ImageURL { get; set; }
    }
}
